# === KẾT NỐI DATABASE LOCAL ===
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=SEAL_Hackathon_G06;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# === Cấu hình ddl-auto cho Local ===
# Trong lúc dev, bạn nên đổi từ 'none' thành 'update' để Hibernate tự động sửa bảng khi bạn thêm thuộc tính mới trong Java, đỡ phải chạy file SQL thủ công
spring.jpa.hibernate.ddl-auto=update